"""your comment.

Revision ID: 44e6799007fc
Revises: 
Create Date: 2025-05-31 05:01:27.237942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e6799007fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_manager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('request',
    sa.Column('RequestID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserEmail', sa.String(length=255), nullable=False),
    sa.Column('Budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('AdditionalDetails', sa.Text(), nullable=True),
    sa.Column('Status', sa.Enum('Pending', 'Accepted', 'Approved', 'Rejected', name='status_enum'), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=False),
    sa.Column('TypeOfBuilding', sa.String(length=50), nullable=False),
    sa.Column('Area', sa.Float(), nullable=False),
    sa.Column('NumberOfFloors', sa.Integer(), nullable=False),
    sa.Column('NumberOfRooms', sa.Integer(), nullable=False),
    sa.Column('RoofType', sa.String(length=50), nullable=False),
    sa.Column('AdminReply', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('RequestID')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('TypeOfBuilding', sa.String(length=50), nullable=False),
    sa.Column('Area', sa.Float(), nullable=False),
    sa.Column('NumberOfFloors', sa.Integer(), nullable=False),
    sa.Column('NumberOfRooms', sa.Integer(), nullable=False),
    sa.Column('RoofType', sa.String(length=50), nullable=False),
    sa.Column('site_contractor_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['site_contractor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('site_cont_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['p_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['site_cont_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('site_cont_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['p_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['site_cont_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phase1', sa.Boolean(), nullable=True),
    sa.Column('phase2', sa.Boolean(), nullable=True),
    sa.Column('phase3', sa.Boolean(), nullable=True),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('site_cont_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['site_cont_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('description_of_works', sa.Text(), nullable=False),
    sa.Column('equipment_machinery', sa.String(length=255), nullable=True),
    sa.Column('date_of_inspection', sa.Date(), nullable=False),
    sa.Column('Status', sa.Enum('Pending', 'Accepted', 'Approved', 'Rejected', name='status_enum'), nullable=True),
    sa.Column('site_cont_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('AdminReply', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['site_cont_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_request')
    op.drop_table('project_progress')
    op.drop_table('material')
    op.drop_table('employee')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('request')
    op.drop_table('construction_manager')
    # ### end Alembic commands ###
